package nginx

import (
	"bytes"
	"database/sql"
	"encoding/json"
	"fmt"
	"log"
	"os"
	"os/exec"
	"regexp"
	"strings"
	"sync"
	"time"

	"lambs-server-go/internal/db"
	"lambs-server-go/internal/execpath"
	"lambs-server-go/internal/models"
)

// Sync regenerates the managed nginx config on Web1 and reloads nginx.
func Sync() {
	rows, err := db.DB.Query("SELECT name, base_path, COALESCE(backend_url,''), COALESCE(port,'') FROM projects WHERE base_path IS NOT NULL AND base_path != ''")
	if err != nil {
		return
	}
	defer rows.Close()
	var projects []models.Project
	for rows.Next() {
		var p models.Project
		rows.Scan(&p.Name, &p.BasePath, &p.BackendURL, &p.Port)
		projects = append(projects, p)
	}
	conf := buildConfig(projects)
	// 3 attempts with backoff — a transient Web1 outage must not silently
	// leave the managed config stale forever.
	for attempt := 1; attempt <= 3; attempt++ {
		if err := pushConfig(conf); err == nil {
			return
		}
		if attempt == 3 {
			log.Printf("nginx: sync failed after 3 attempts, config may be stale")
			return
		}
		time.Sleep(retryDelay)
	}
}

// web1Host is the ssh target for config pushes (WEB1_SSH_HOST env,
// e.g. ubuntu@<web1-address>). No hardcoded default — a wrong hardcoded
// host would silently push configs to the wrong machine.
var web1Host = os.Getenv("WEB1_SSH_HOST")

// retryDelay backs off between Sync push attempts; tests shrink it.
var retryDelay = 2 * time.Second

// gateHost is App1's own address as reachable from Web1 (GATE_HOST env,
// e.g. <app1-address>:3602). Deployment-specific, never hardcoded.
var gateHost = os.Getenv("GATE_HOST")

// sshRun runs one remote command over ssh; tests swap it for a stub.
var sshRun = func(host, remoteCmd string, stdin []byte) ([]byte, error) {
	cmd := exec.Command(execpath.Path("ssh"), "-o", "StrictHostKeyChecking=no", "-o", "ConnectTimeout=5",
		host, remoteCmd)
	cmd.Stdin = bytes.NewReader(stdin)
	return cmd.CombinedOutput()
}

func pushConfig(conf string) error {
	if web1Host == "" {
		log.Printf("nginx: WEB1_SSH_HOST not configured, skipping config push")
		return fmt.Errorf("WEB1_SSH_HOST not set")
	}
	if out, err := sshRun(web1Host, "sudo tee /etc/nginx/sites-available/lambs-managed.conf > /dev/null", []byte(conf)); err != nil {
		log.Printf("nginx: sync write failed: %v — %s", err, string(out))
		return err
	}
	if out, err := sshRun(web1Host, "sudo nginx -t && sudo systemctl reload nginx", nil); err != nil {
		log.Printf("nginx: sync reload failed: %v — %s", err, string(out))
		return err
	}
	return nil
}

// AutoRefresh periodically syncs user counts from project datasources.
// Counts run concurrently (semaphore-capped) — the old serial loop let one
// unreachable DB stall the whole round for its dial timeout (R13 perf).
func AutoRefresh() {
	for {
		time.Sleep(1 * time.Minute)
		autoRefreshOnce()
	}
}

// autoRefreshOnce runs one refresh round. Extracted from the loop so the
// scheduling is testable without waiting a minute — same pattern as
// healthOnce/idleOnce in runtime.
func autoRefreshOnce() {
	sem := make(chan struct{}, 8)
	rows, err := db.DB.Query("SELECT id, dsn FROM projects WHERE dsn IS NOT NULL AND dsn != '' AND dsn != '—'")
	if err != nil {
		return
	}
	type job struct{ id, dsn string }
	var jobs []job
	for rows.Next() {
		var id, dsn string
		rows.Scan(&id, &dsn)
		jobs = append(jobs, job{id, dsn})
	}
	rows.Close()
	var wg sync.WaitGroup
	for _, j := range jobs {
		wg.Add(1)
		go func(j job) {
			defer wg.Done()
			sem <- struct{}{}
			defer func() { <-sem }()
			refreshOne(j.id, j.dsn)
		}(j)
	}
	wg.Wait()
}

// refreshOne updates one project's user count and 用户数 feature.
func refreshOne(id, dsn string) {
	n := db.SyncUserCount(dsn)
	db.DB.Exec("UPDATE projects SET users_count=$1, updated_at=NOW() WHERE id=$2", n, id)
	var fRaw sql.NullString
	db.DB.QueryRow("SELECT features::text FROM projects WHERE id=$1", id).Scan(&fRaw)
	if fRaw.Valid && fRaw.String != "" {
		var feats []map[string]interface{}
		if json.Unmarshal([]byte(fRaw.String), &feats) == nil {
			found := false
			for i, f := range feats {
				if l, ok := f["label"]; ok && l == "用户数" {
					feats[i]["value"] = n
					found = true
					break
				}
			}
			if !found {
				feats = append(feats, map[string]interface{}{"label": "用户数", "value": n})
			}
			b, _ := json.Marshal(feats)
			db.DB.Exec("UPDATE projects SET features=$1 WHERE id=$2", string(b), id)
		}
	}
}

func buildConfig(projects []models.Project) string {
	gate := gateHost
	if gate == "" {
		gate = "127.0.0.1:3602" // unreachable from Web1 — sync will be skipped upstream
	}
	lines := []string{"# Auto-generated by Lambs. Last sync: managed projects.", "",
		"# Lambs maintenance/offline page handler",
		"location = /lambs-offline {",
		"    internal;",
		"    proxy_pass http://" + gate + "/api/gate/offline-page;",
		"    proxy_set_header X-Original-URI $request_uri;",
		"    proxy_set_header Host $host;",
		"    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;",
		"}", ""}
	// bpRe is the charset gate for nginx location paths — anything else could
	// inject raw config directives into the managed vhost.
	bpRe := regexp.MustCompile(`^[a-zA-Z0-9][a-zA-Z0-9._/-]*$`)
	for _, p := range projects {
		bp := strings.TrimPrefix(p.BasePath, "/")
		if !bpRe.MatchString(bp) {
			log.Printf("nginx: skipping project %s — base_path %q is not a safe nginx path", p.ID, p.BasePath)
			continue
		}
		// Comment injection: a newline in the name would start a new directive line.
		name := strings.ReplaceAll(p.Name, "\n", " ")
		name = strings.ReplaceAll(name, "\r", " ")
		// Web1 must reach the project through App1's on-demand TCP proxy
		// (App1-TS:<port>). backend_url is the proxy's internal target on
		// App1 and is NOT reachable from Web1 — using it directly here was
		// wrong host semantics.
		appHost := gate
		if i := strings.LastIndex(gate, ":"); i > 0 {
			appHost = gate[:i]
		}
		apiTarget := "http://" + appHost + ":" + p.Port
		if p.Port == "" {
			apiTarget = p.BackendURL
			if apiTarget == "" {
				continue
			}
			if !strings.HasPrefix(apiTarget, "http://") && !strings.HasPrefix(apiTarget, "https://") {
				apiTarget = "http://" + apiTarget
			}
		}
		logoURL := "http://" + gate + "/api/gate/project-logo?path=/%s"
		checkURL := "http://" + gate + "/api/gate/check-internal?path=/%s"
		lines = append(lines, fmt.Sprintf(`
# %s — Lambs managed
location = /%s/favicon.svg {
    proxy_pass `+logoURL+`;
    proxy_set_header Host $host;
    add_header Cache-Control "public, max-age=120";
}
location = /lambs-gate-%s {
    internal;
    proxy_pass `+checkURL+`;
    proxy_pass_request_body off;
    proxy_set_header Content-Length "";
    proxy_set_header Host $host;
}
location /%s/api/ {
    auth_request /lambs-gate-%s;
    proxy_pass %s/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
location /%s {
    auth_request /lambs-gate-%s;
    error_page 403 = /lambs-offline;
    try_files $uri $uri/ /%s/index.html;
}`, name, bp, bp, bp, bp,
			bp, bp, apiTarget, bp, bp, bp))
	}
	return strings.Join(lines, "\n")
}
