package nginx

import (
	"bytes"
	"database/sql"
	"encoding/json"
	"fmt"
	"log"
	"os/exec"
	"strings"
	"time"

	"lambs-server-go/internal/db"
	"lambs-server-go/internal/models"
)

// Sync regenerates the managed nginx config on Web1 and reloads nginx.
func Sync() {
	rows, err := db.DB.Query("SELECT name, base_path, COALESCE(backend_url,''), COALESCE(port,'') FROM projects WHERE base_path IS NOT NULL AND base_path != ''")
	if err != nil {
		return
	}
	defer rows.Close()
	var projects []models.Project
	for rows.Next() {
		var p models.Project
		rows.Scan(&p.Name, &p.BasePath, &p.BackendURL, &p.Port)
		projects = append(projects, p)
	}
	conf := buildConfig(projects)
	cmd := exec.Command("ssh", "-o", "StrictHostKeyChecking=no", "-o", "ConnectTimeout=5",
		"ubuntu@100.126.18.126", "sudo tee /etc/nginx/sites-available/lambs-managed.conf > /dev/null")
	cmd.Stdin = bytes.NewReader([]byte(conf))
	if out, err := cmd.CombinedOutput(); err != nil {
		log.Printf("nginx: sync write failed: %v — %s", err, string(out))
		return
	}
	cmd = exec.Command("ssh", "-o", "StrictHostKeyChecking=no", "-o", "ConnectTimeout=5",
		"ubuntu@100.126.18.126", "sudo nginx -t && sudo systemctl reload nginx")
	if out, err := cmd.CombinedOutput(); err != nil {
		log.Printf("nginx: sync reload failed: %v — %s", err, string(out))
	}
}

// AutoRefresh periodically syncs user counts from project datasources.
func AutoRefresh() {
	for {
		time.Sleep(1 * time.Minute)
		rows, err := db.DB.Query("SELECT id, dsn FROM projects WHERE dsn IS NOT NULL AND dsn != '' AND dsn != '—'")
		if err != nil {
			continue
		}
		for rows.Next() {
			var id, dsn string
			rows.Scan(&id, &dsn)
			n := db.SyncUserCount(dsn)
			db.DB.Exec("UPDATE projects SET users_count=$1, updated_at=NOW() WHERE id=$2", n, id)
			var fRaw sql.NullString
			db.DB.QueryRow("SELECT features::text FROM projects WHERE id=$1", id).Scan(&fRaw)
			if fRaw.Valid && fRaw.String != "" {
				var feats []map[string]interface{}
				if json.Unmarshal([]byte(fRaw.String), &feats) == nil {
					found := false
					for i, f := range feats {
						if l, ok := f["label"]; ok && l == "用户数" {
							feats[i]["value"] = n
							found = true
							break
						}
					}
					if !found {
						feats = append(feats, map[string]interface{}{"label": "用户数", "value": n})
					}
					b, _ := json.Marshal(feats)
					db.DB.Exec("UPDATE projects SET features=$1 WHERE id=$2", string(b), id)
				}
			}
		}
		rows.Close()
	}
}

func buildConfig(projects []models.Project) string {
	lines := []string{"# Auto-generated by Lambs. Last sync: managed projects.", "",
		"# Lambs maintenance/offline page handler",
		"location = /lambs-offline {",
		"    internal;",
		"    proxy_pass http://100.92.91.11:3602/api/gate/offline-page;",
		"    proxy_set_header X-Original-URI $request_uri;",
		"    proxy_set_header Host $host;",
		"    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;",
		"}", ""}
	for _, p := range projects {
		backend := p.BackendURL
		if backend == "" {
			backend = "http://127.0.0.1:" + p.Port
		}
		if !strings.HasPrefix(backend, "http://") && !strings.HasPrefix(backend, "https://") {
			backend = "http://" + backend
		}
		bp := strings.TrimPrefix(p.BasePath, "/")
		lines = append(lines, fmt.Sprintf(`
# %s — Lambs managed
location = /%s/favicon.svg {
    proxy_pass http://100.92.91.11:3602/api/gate/project-logo?path=/%s;
    proxy_set_header Host $host;
    add_header Cache-Control "public, max-age=120";
}
location = /lambs-gate-%s {
    internal;
    proxy_pass http://100.92.91.11:3602/api/gate/check-internal?path=/%s;
    proxy_pass_request_body off;
    proxy_set_header Content-Length "";
    proxy_set_header Host $host;
}
location /%s/api/ {
    auth_request /lambs-gate-%s;
    proxy_pass %s/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
location /%s {
    auth_request /lambs-gate-%s;
    error_page 403 = /lambs-offline;
    try_files $uri $uri/ /%s/index.html;
}`, p.Name, bp, bp, bp, bp,
			bp, bp, backend, bp, bp, bp))
	}
	return strings.Join(lines, "\n")
}
