package handlers

import (
	crand "crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"os"
	"strconv"
	"strings"

	"lambs-server-go/internal/auth"
	"lambs-server-go/internal/db"
	"lambs-server-go/internal/models"

	"golang.org/x/crypto/bcrypt"
)

func sha256Hex(s string) string {
	h := sha256.Sum256([]byte(s))
	return hex.EncodeToString(h[:])
}

func ListUsers(w http.ResponseWriter, r *http.Request) {
	search := r.URL.Query().Get("search")
	roleFilter := r.URL.Query().Get("role")
	query := "SELECT id, username, name, email, role, status, COALESCE(project_access::text,'[]'), COALESCE(avatar_url::text,''), COALESCE(avatar_thumb,''), COALESCE(last_login::text,'') FROM users WHERE 1=1"
	var args []interface{}
	argIdx := 0
	if search != "" { argIdx++; query += " AND (username ILIKE $" + strconv.Itoa(argIdx) + " OR name ILIKE $" + strconv.Itoa(argIdx) + " OR email ILIKE $" + strconv.Itoa(argIdx) + ")"; args = append(args, "%"+search+"%") }
	if roleFilter != "" && roleFilter != "all" { argIdx++; if roleFilter == "viewer" { query += " AND (role=$" + strconv.Itoa(argIdx) + " OR role IS NULL OR role='')" } else { query += " AND role=$" + strconv.Itoa(argIdx) }; args = append(args, roleFilter) }
	query += " ORDER BY created_at DESC"
	rows, err := db.DB.Query(query, args...)
	if err != nil { log.Printf("ListUsers: %v", err); auth.JSONErr(w, 500, "查询用户失败"); return }
	defer rows.Close()
	users := []models.User{}
	for rows.Next() {
		var u models.User
		var pa, av, avThumb string
		if err := rows.Scan(&u.ID, &u.Username, &u.Name, &u.Email, &u.Role, &u.Status, &pa, &av, &avThumb, &u.LastLogin); err != nil {
			continue
		}
		u.ProjectAccess = pa
		if avThumb != "" { av = avThumb } else if len(av) > 64*1024 { av = "" }
		u.AvatarURL = av
		users = append(users, u)
	}
	if users == nil { users = []models.User{} }
	var all, super, projAdmin, viewer int
	db.DB.QueryRow(`SELECT COUNT(*),
		COUNT(*) FILTER (WHERE role='super_admin'),
		COUNT(*) FILTER (WHERE role='project_admin'),
		COUNT(*) FILTER (WHERE role='viewer' OR role IS NULL OR role='')
		FROM users`).Scan(&all, &super, &projAdmin, &viewer)
	auth.JSONOK(w, map[string]interface{}{"users": users, "counts": map[string]int{"all": all, "super_admin": super, "project_admin": projAdmin, "viewer": viewer}, "total": len(users), "page": 1, "page_size": len(users)})
}

func CreateUser(w http.ResponseWriter, r *http.Request) {
	var req struct {
		Username      string `json:"username"`
		Name          string `json:"name"`
		Email         string `json:"email"`
		Role          string `json:"role"`
		Password      string `json:"password"`
		ProjectAccess string `json:"project_access"`
		AvatarURL     string `json:"avatar_url"`
	}
	json.NewDecoder(r.Body).Decode(&req)
	pwd := req.Password
	autoGenerated := pwd == ""
	if autoGenerated {
		pwd = os.Getenv("INITIAL_PASSWORD")
		if pwd == "" {
			b := make([]byte, 8)
			crand.Read(b)
			pwd = hex.EncodeToString(b)
		}
	}
	hash, _ := bcrypt.GenerateFromPassword([]byte(sha256Hex(pwd)), bcrypt.DefaultCost)
	u := models.User{Username: req.Username, Name: req.Name, Email: req.Email, Role: req.Role, ProjectAccess: req.ProjectAccess, AvatarURL: req.AvatarURL}
	pa := u.ProjectAccess; if pa == "" { pa = "[]" }
	av := u.AvatarURL; if av == "" { av = "" }
	avThumb := ""
	if u.AvatarURL != "" {
		if t, err := makeThumb(u.AvatarURL, 128); err == nil && t != u.AvatarURL {
			avThumb = t
		}
	}
	err := db.DB.QueryRow("INSERT INTO users (id, username, name, email, password_hash, role, status, project_access, avatar_url, avatar_thumb) VALUES (gen_random_uuid(),$1,$2,$3,$4,$5,'active',$6::jsonb,$7,$8) RETURNING id::text",
		u.Username, u.Name, u.Email, string(hash), u.Role, pa, av, avThumb).Scan(&u.ID)
	if err != nil { auth.JSONErr(w, 400, "创建失败: "+err.Error()); return }
	auditLog(r, "创建用户", u.Username, "role="+u.Role)
	// Auto-generated password must reach the admin (frontend toasts res.data.password) —
	// otherwise a user created without one can never log in.
	type createUserResp struct {
		models.User
		Password string `json:"password,omitempty"`
	}
	resp := createUserResp{User: u}
	if autoGenerated {
		resp.Password = pwd
	}
	auth.JSONCreated(w, resp)
}

func UpdateUser(w http.ResponseWriter, r *http.Request, id string) {
	var u models.User
	json.NewDecoder(r.Body).Decode(&u)
	if u.Username == "" { auth.JSONErr(w, 400, "用户名不能为空"); return }
	if u.Role != "super_admin" && u.Role != "project_admin" && u.Role != "viewer" { auth.JSONErr(w, 400, "角色不合法"); return }
	if u.Status != "active" && u.Status != "disabled" { auth.JSONErr(w, 400, "状态不合法"); return }
	pa := u.ProjectAccess; if pa == "" { pa = "[]" }
	av := u.AvatarURL; if av == "" { av = "" }
	avThumb := ""
	if strings.HasPrefix(u.AvatarURL, "data:") {
		if t, err := makeThumb(u.AvatarURL, 128); err == nil && t != u.AvatarURL {
			avThumb = t
		}
	}
	if _, err := db.DB.Exec("UPDATE users SET username=$1, name=$2, email=$3, role=$4, status=$5, project_access=$6::jsonb, avatar_url=$7, avatar_thumb=CASE WHEN $7='' THEN '' ELSE COALESCE(NULLIF($8,''), avatar_thumb) END WHERE id=$9", u.Username, u.Name, u.Email, u.Role, u.Status, pa, av, avThumb, id); err != nil {
		auth.JSONErr(w, 400, "修改失败: 用户名可能已存在")
		return
	}
	auditLog(r, "修改用户", u.Username, fmt.Sprintf("role=%s status=%s", u.Role, u.Status))
	auth.JSONOK(w, map[string]string{"updated": id})
}

func DeleteUser(w http.ResponseWriter, r *http.Request, id string) {
	var uname string
	if err := db.DB.QueryRow("SELECT username FROM users WHERE id=$1", id).Scan(&uname); err != nil {
		auth.JSONErr(w, 404, "用户不存在")
		return
	}
	if _, err := db.DB.Exec("DELETE FROM users WHERE id=$1", id); err != nil {
		auth.JSONErr(w, 500, "删除失败")
		return
	}
	auditLog(r, "删除用户", uname, "用户账号已删除")
	auth.JSONOK(w, map[string]string{"deleted": id})
}

func ResetPassword(w http.ResponseWriter, r *http.Request, id string) {
	var req struct{ NewPassword string `json:"new_password"` }
	json.NewDecoder(r.Body).Decode(&req)
	if req.NewPassword == "" { auth.JSONErr(w, 400, "请输入新密码"); return }
	if len(req.NewPassword) < 6 { auth.JSONErr(w, 400, "新密码至少6位"); return }
	hash, _ := bcrypt.GenerateFromPassword([]byte(sha256Hex(req.NewPassword)), bcrypt.DefaultCost)
	if _, err := db.DB.Exec("UPDATE users SET password_hash=$1, token_version=COALESCE(token_version,0)+1 WHERE id=$2", string(hash), id); err != nil {
		auth.JSONErr(w, 500, "重置失败")
		return
	}
	var uname string
	db.DB.QueryRow("SELECT username FROM users WHERE id=$1", id).Scan(&uname)
	auditLog(r, "重置密码", uname, "管理员重置用户密码")
	auth.JSONOK(w, map[string]bool{"ok": true})
}
